### ISSUE TITLE
There is a wrong

### ISSUE THREAD

**Issue by zhaodagang** [Cap32/babel-register-cli#2]
test.js 
require("babel-register");
let model = require("./mm.js");

mm.js
let a = {
  t:11,
  t2:22

}
export default a;

PS F:\node> node test
F:\node\mm.js:8
export default a;
^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at loader (F:\node\node_modules\_babel-register@6.26.0@babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (F:\node\node_modules\_babel-register@6.26.0@babel-register\lib\node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

**Comment by Cap32** [comment]
1. You're using [babel-register](https://github.com/babel/babel/tree/6.x/packages/babel-register), but not [babel-register-cli](https://github.com/Cap32/babel-register-cli)
2. You need [babel-plugin-transform-es2015-modules-commonjs](https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/) to transform ES modules

**Comment by zhaodagang** [comment]
I install  babel-register,  babel-register-cli    babel-plugin-transform-es2015-modules-commonjs 

It is still wrong .
Like up these code，how I shoud do?

**Comment by Cap32** [comment]
Did you use the babel plugin via [.babelrc](https://babeljs.io/docs/usage/babelrc/)?

**Comment by zhaodagang** [comment]
i only think oprate es6 code  in node.js，

**Comment by zhaodagang** [comment]
For example , in node.js like this:
 import a from 'bb.js'

How do?

**Comment by zhaodagang** [comment]
我只是想在nodde.js中，使用  import  或者  export等es6.
应该怎么做，告诉我下使用流程。

**Comment by Cap32** [comment]
You may need [this](https://www.baidu.com/s?ie=utf-8&f=3&rsv_bp=0&rsv_idx=1&tn=baidu&wd=node.js%20%E4%BD%BF%E7%94%A8es6%20module&rsv_pq=fcf49f10000236ed&rsv_t=462dg%2FFlgpMDz5uG%2BBcI966qPZobWb58OIMbI%2BIuPLPvje6s%2BjN%2FNnGqzNw&rqlang=cn&rsv_enter=1&rsv_sug3=31&rsv_sug1=37&rsv_sug7=100&rsv_sug2=0&prefixsug=node.js%2520%25E4%25BD%25BF%25E7%2594%25A8&rsp=1&inputT=16374&rsv_sug4=16875)
